language: erlang

env:
   - ST=Pharo-3.0
   - ST=Pharo-4.0

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME 
   - wget -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

script: $BUILDER_CI_HOME/testTravisCI.sh -verbose
