language: erlang

install:
   - cd ~/
   - git clone git://github.com/renggli/builder.git
   - cd ~/builder/images
   - wget https://ci.lille.inria.fr/pharo/view/Pharo%201.4/job/Pharo%201.4/lastStableBuild/artifact/Pharo-1.4.zip
   - unzip Pharo-1.4.zip
   - cd Pharo-1.4
   - mv *.sources ~/builder/sources
   - mv *.changes ..
   - mv *.image ..
   - cd ~/Player-ST
   - cp script/PlayerST.st ~/builder/scripts/
   - cd ~/builder

script:
   - ./build.sh -i Pharo-1.4 -s PlayerST.st -o Player-ST