as yet unclassified
initializeInterfaceCodes
	PlayerNullCode := 256.
	"// /dev/null analogue"
	PlayerPlayerCode := 1.
	"// the server itself"
	PlayerPowerCode := 2.
	"// power subsystem"
	PlayerGripperCode := 3.
	"// gripper"
	PlayerPosition2dCode := 4.
	"// device that moves"
	PlayerSonarCode := 5.
	"// fixed range-finder"
	PlayerLaserCode := 6.
	"// scanning range-finder"
	PlayerBlobfinderCode := 7.
	"// visual blobfinder"
	PlayerPtzCode := 8.
	"// pan-tilt-zoom unit"
	PlayerAudioCode := 9.
	"// audio I/O"
	PlayerFiducialCode := 10.
	"// fiducial detector"
	PlayerSpeechCode := 12.
	"// speech I/O"
	PlayerGpsCode := 13.
	"// GPS unit"
	PlayerBumperCode := 14.
	"// bumper array"
	PlayerTruthCode := 15.
	"// ground-truth (Stage)"
	PlayerDioCode := 20.
	"// digital I/O"
	PlayerAioCode := 21.
	"// analog I/O"
	PlayerIrCode := 22.
	"// IR array"
	PlayerWifiCode := 23.
	"// wifi card status"
	PlayerWaveformCode := 24.
	"// fetch raw waveforms"
	PlayerLocalizeCode := 25.
	"// localization"
	PlayerMcomCode := 26.
	"// multicoms"
	PlayerSoundCode := 27.
	"// sound file playback"
	PlayerAudiodspCode := 28.
	"// audio dsp I/O"
	PlayerAudiomixerCode := 29.
	"// audio I/O"
	PlayerPosition3dCode := 30.
	"// 3-D position"
	PlayerSimulationCode := 31.
	"// simulators"
	PlayerServiceAdvCode := 32.
	"// LAN advertisement"
	PlayerBlinkenlightCode := 33.
	"// blinking lights"
	PlayerNomadCode := 34.
	"// Nomad robot"
	PlayerCameraCode := 40.
	"// camera device(gazebo)"
	PlayerMapCode := 42.
	"// get a map"
	PlayerPlannerCode := 44.
	"// 2D motion planner"
	PlayerLogCode := 45.
	"// log R/W control"
	PlayerEnergyCode := 46.
	"// energy charging"
	PlayerJoystickCode := 49.
	"// Joystick"
	PlayerSpeechRecognitionCode := 50.
	"speech I/O"
	PlayerOpaqueCode := 51.
	"plugin interface"
	PlayerPosition1dCode := 52.
	"1-D position"
	PlayerActarrayCode := 53.
	"Actuator Array interface"
	PlayerLimbCode := 54.
	"Limb interface"
	PlayerGraphics2dCode := 55.
	"Graphics2D interface"
	PlayerRfidCode := 56.
	"RFID reader interface"
	PlayerWsnCode := 57.
	"WSN interface"
	PlayerGraphics3dCode := 58.
	"Graphics3D interface"
	PlayerHealthCode := 59.
	"Statgrab Health interface"
	PlayerImuCode := 60.
	"Inertial Measurement Unit interface"
	PlayerPointcloud3dCode := 61
	"3-D point cloud"
